import 'package:flutter/material.dart';
import 'package:seeds/design/app_colors.dart';

class AppColorSchemes {
  static const ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: AppColors.green1,
    onPrimary: AppColors.white,
    primaryContainer: AppColors.darkGreen2,
    onPrimaryContainer: AppColors.white,
    secondary: AppColors.green2,
    onSecondary: AppColors.white,
    secondaryContainer: AppColors.lightGreen1,
    onSecondaryContainer: AppColors.white,
    tertiary: AppColors.green3,
    onTertiary: AppColors.white,
    tertiaryContainer: AppColors.lightGreen2,
    onTertiaryContainer: AppColors.white,
    error: AppColors.red1,
    onError: AppColors.white,
    errorContainer: AppColors.red1,
    onErrorContainer: AppColors.white,
    background: AppColors.primary,
    onBackground: AppColors.white,
    surface: AppColors.primary,
    onSurface: AppColors.white,
    surfaceVariant: AppColors.darkGreen3,
    onSurfaceVariant: AppColors.grey1,
    outline: AppColors.grey2,
    outlineVariant: AppColors.grey3,
    shadow: AppColors.black,
    scrim: AppColors.black,
    inverseSurface: AppColors.white,
    onInverseSurface: AppColors.primary,
    inversePrimary: AppColors.green1,
    surfaceTint: AppColors.green1,
  );

  static const ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: AppColors.green1,
    onPrimary: AppColors.white,
    primaryContainer: AppColors.lightGreen5,
    onPrimaryContainer: AppColors.primary,
    secondary: AppColors.green2,
    onSecondary: AppColors.white,
    secondaryContainer: AppColors.lightGreen5,
    onSecondaryContainer: AppColors.primary,
    tertiary: AppColors.green3,
    onTertiary: AppColors.white,
    tertiaryContainer: AppColors.lightGreen5,
    onTertiaryContainer: AppColors.primary,
    error: AppColors.red1,
    onError: AppColors.white,
    errorContainer: AppColors.red1,
    onErrorContainer: AppColors.white,
    background: AppColors.white,
    onBackground: AppColors.black,
    surface: AppColors.white,
    onSurface: AppColors.black,
    surfaceVariant: AppColors.lightGrey,
    onSurfaceVariant: AppColors.black,
    outline: AppColors.borderGrey,
    outlineVariant: AppColors.grey,
    shadow: AppColors.black,
    scrim: AppColors.black,
    inverseSurface: AppColors.primary,
    onInverseSurface: AppColors.white,
    inversePrimary: AppColors.green1,
    surfaceTint: AppColors.green1,
  );
}
